### PR TITLE
Make fastboot guard

### PR DESCRIPTION
**Pull request by tschoartschi**
I implemented a simple fastboot guard so that the fastboot server can start and is not crashing while booting. I tried to implement a fixed base on the following discussions: ember-fastboot/ember-cli-fastboot#105 and plusacht/ember-bootstrap-datetimepicker#75

### CODE REVIEW

**Comment by kennethkalmer** [comment]
Thanks for this! Could you help me understand how to verify the issue so I can understand the fix? I've been thinking about fastboot lately, so this is a great way to get in :)

**Comment by tschoartschi** [comment]
When I started my app with ```ember fastboot```, I got the following error:

```
TypeError: Cannot read property 'pointerEnabled' of undefined
    at .../fastboot-dist/fastboot/bower_components/nouislider/distribute/nouislider.js:135:1
    at .../fastboot-dist/fastboot/bower_components/nouislider/distribute/nouislider.js:26:1
    at .../fastboot-dist/fastboot/bower_components/nouislider/distribute/nouislider.js:29:1
    at Sandbox.VMSandbox.eval (.../node_modules/ember-fastboot-server/lib/sandboxes/vm.js:14:14)
    at new EmberApp (.../node_modules/ember-fastboot-server/lib/ember-app.js:41:11)
    at new FastBootServer (.../node_modules/ember-fastboot-server/lib/server.js:33:14)
    at .../node_modules/ember-cli-fastboot/lib/commands/fastboot.js:32:22
    at lib$rsvp$$internal$$tryCatch (.../node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (.../node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (.../node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (.../node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```
This basically means that nouislider.js uses some functionality which is not available on server side rendering. My fix just excludes all libraries which are not available in fastboot mode. Maybe you could write some polyfills but for our app it was/is sufficient to just exclude things which do not work on the server.

Does this make sense?

**Comment by kennethkalmer** [comment]
Makes perfect sense! Will have to see how it can be added to the tests as
well.
On Mon, 09 May 2016 at 12:37 PM tschoartschi <notifications@github.com>
wrote:

> When I started my app with ember fastboot, I got the following error:
>
> TypeError: Cannot read property 'pointerEnabled' of undefined
>     at .../fastboot-dist/fastboot/bower_components/nouislider/distribute/nouislider.js:135:1
>     at .../fastboot-dist/fastboot/bower_components/nouislider/distribute/nouislider.js:26:1
>     at .../fastboot-dist/fastboot/bower_components/nouislider/distribute/nouislider.js:29:1
>     at Sandbox.VMSandbox.eval (.../node_modules/ember-fastboot-server/lib/sandboxes/vm.js:14:14)
>     at new EmberApp (.../node_modules/ember-fastboot-server/lib/ember-app.js:41:11)
>     at new FastBootServer (.../node_modules/ember-fastboot-server/lib/server.js:33:14)
>     at .../node_modules/ember-cli-fastboot/lib/commands/fastboot.js:32:22
>     at lib$rsvp$$internal$$tryCatch (.../node_modules/rsvp/dist/rsvp.js:1036:16)
>     at lib$rsvp$$internal$$invokeCallback (.../node_modules/rsvp/dist/rsvp.js:1048:17)
>     at lib$rsvp$$internal$$publish (.../node_modules/rsvp/dist/rsvp.js:1019:11)
>     at lib$rsvp$asap$$flush (.../node_modules/rsvp/dist/rsvp.js:1198:9)
>     at _combinedTickCallback (node.js:370:9)
>     at process._tickCallback (node.js:401:11)
>
> This basically means that nouislider.js uses some functionality which is
> not available on server side rendering. My fix just excludes all libraries
> which are not available in fastboot mode. Maybe you could write some
> polyfills but for our app it was/is sufficient to just exclude things which
> do not work on the server.
>
> Does this make sense?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/kennethkalmer/ember-cli-nouislider/pull/26#issuecomment-217831396>
>
-- 

Kenneth Kalmer
@kennethkalmer
http://www.opensourcery.co.za

**Comment by tschoartschi** [comment]
@kennethkalmer I accidentally put the fastboot guard into the wrong file. With my latest commit I switched the guard to index.js. If you have any questions let me know

**Comment by Ramblurr** [comment]
Any update on this?

**Comment by kennethkalmer** [comment]
Thanks for this and sorry for letting it sit. Will prepare a patch release shortly

**Comment by kennethkalmer** [comment]
I just released 0.10.0, could you please let me know if there are any regressions?

**Pull request merged**
