### PR TITLE
bring back snap and pips, somehow lost in recent commit

### PR DESCRIPTION
**Pull request by kbullaughey**

### CODE REVIEW

**Comment by davidgoli** [comment]
:+1:

**Comment by kennethkalmer** [comment]
Thanks! Just having a look at what is up with Travis

**Comment by kennethkalmer** [comment]
poezj

Will upgrade the chain separately

**Comment by kennethkalmer** [comment]
0.7.0 just got published with this fix and #19

**Comment by kbullaughey** [comment]
Thanks!

**Pull request merged**
