### PR TITLE
Added Padding option

### PR DESCRIPTION
**Pull request by sonnyt**
https://refreshless.com/nouislider/slider-options/#section-padding

### CODE REVIEW

**Comment by cea2k** [comment]
I'd like to have this available as padding is not currently supported. Hey @kennethkalmer is there something else missing we can help with?
Thanks in advance.

**Comment by scottkidder** [comment]
I needed this option as well so I have a branch in my fork with both this PR and #68 [here](https://github.com/scottkidder/ember-cli-nouislider/tree/dev) if it helps

**Comment by scottkidder** [comment]
@kennethkalmer Would be great to get this one merged. I am now using it in production and it works exactly as expected. The documentation/example that @sonnyt put together is top-notch as well. :+1:

**Comment by scottkidder** [comment]
@kennethkalmer Possible to get this merged and released?

I'm happy to help out with this project if you're too busy or no longer using it. :)

**Comment by kennethkalmer** [comment]
Thanks @sonnyt for the contribution, and my sincere apologies that this took so long to land. I'm preparing a new release.

**Pull request merged**
