### PR TITLE
Support disabled attribute

### PR DESCRIPTION
**Pull request by alexspeller**
Support disabled attribute of noUiSlider with ability to dynamically change it

### CODE REVIEW

**Comment by kennethkalmer** [comment]
Thanks @alexspeller! I'll take this for a test drive later today and get back to you.

**Comment by dustinspecker** [comment]
Any chance of this being merged in? We tried @alexspeller changes on a current version of this package and it worked perfectly. We'd love to have this feature merged in.

**Comment by kennethkalmer** [comment]
I'm just bumping to ember 2.8.0 and then I'll release a new version!

**Comment by kennethkalmer** [comment]
0.10.0 has been tagged and published to npm! Thanks for your contribution!

**Pull request merged**
