### PR TITLE
Added ember-cli versions >= 0.2.3 addon install syntax

### PR DESCRIPTION
**Pull request by DominikAngerer**
Added ember-cli versions >= 0.2.3 addon install syntax

### CODE REVIEW

**Comment by DominikAngerer** [comment]
If you are facing a problem like:

```
ember install ember-cli-nouislider
version: 0.2.3
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/leongersen/noUiSlider.git#7.0.10
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```

Simply use: `ember generate ember-cli-nouislider` and the issue is gone. There is already a pull request to ember cli which should fix this issue: https://github.com/ember-cli/ember-cli/pull/3846

**Comment by kennethkalmer** [comment]
@DominikAngerer thanks! Would you mind rephrasing it slightly? Instead of _the new ember-cli_, maybe go for _ember-cli versions >= 0.2.3_ ?

**Comment by kennethkalmer** [comment]
@DominikAngerer I found a good example - https://github.com/Semantic-Org/Semantic-UI-Ember#installation

**Comment by DominikAngerer** [comment]
You're right >= 0.2.3 would be better than "new ember-cli". - Updated.

BR,
Dominik

**Comment by DominikAngerer** [comment]
Also the issue should now be gone - the Pull Request on Ember-cli was merged right after we referenced it there ;)

**Comment by kennethkalmer** [comment]
Thanks @DominikAngerer for the tweaks, tested it on a new `0.2.5` app and it worked out the box :+1:

**Comment by DominikAngerer** [comment]
Also added this as comment before the merge here - the github issue was merged in this version ;)

**Pull request merged**
