### PR TITLE
Add "format" & "pips" support

### PR DESCRIPTION
**Pull request by davidgoli**
https://github.com/kennethkalmer/ember-cli-nouislider/issues/12

### CODE REVIEW

**Comment by kennethkalmer** [comment]
Thanks @davidgoli!

**Comment by davidgoli** [comment]
@kennethkalmer any chance we can get a version bump with this or #14 so npm will install the correct version?

**Comment by kennethkalmer** [comment]
@davidgoli coming right up

**Comment by Sonderstorch** [comment]
Seems, that forwarding the options `pips` and `snap` to `create()` in the component's `setup()`-method has been omitted in one of the last commits...

So the feature added in #13 went south again? And are there any hints how to use `pips` with block params? The only way to use this seems to extend the component, if I'm not missing something.

**Comment by kennethkalmer** [comment]
I'll have a look at this when I update the documentation as well, thanks for pointing out the issues!

**Comment by kbullaughey** [comment]
I've submitted a PR (issue #18) to bring back pips and snap.

**Pull request merged**
