### PR TITLE
Fix actions

### LINKED ISSUE #5: sendAction() not working on 1.12
At least on Ember 1.12.1 the line:
```javascript
      _this.sendAction( changeAction, _this.slider.val() );
```
works only if you change it to:
```javascript
      _this.sendAction( 'change', _this.slider.val() );
```
It is, `sendAction()` must receive the name of the property that holds the action’s name as a value and not the name itself!

### PR DESCRIPTION
**Pull request by knownasilya**
Fixes #5

### CODE REVIEW

**Comment by kennethkalmer** [comment]
@knownasilya thanks so much! 

Two things quickly:

* Could you clean up the `slideAction = this.get('slide')` on line 40 as well please?
* Why the `Ember.run()` wrappers? Just curious and looking to learn on this one.

**Comment by kennethkalmer** [comment]
Before we get this merged, lets have a chat through the API in #5.

**Comment by knownasilya** [comment]
Ember.run prevents unwanted behavior and missed event triggers, since Ember manages when things happen. Since these are events in an external library, the callbacks are not handled automatically by the runloop.

That slideAction check is necessary to make sure to now throw errors in the console if the user hasn't set a `slide='mySlideAction'`.

**Comment by kennethkalmer** [comment]
@knownasilya thanks for your contribution! Just published 0.4.1 as a fix.

**Pull request merged**
